/v1/genders/{id}:
    get:
        tags:
            - genders
        summary: Get a gender
        description: Get a gender. This is a public endpoint.
        operationId: getGender.js
        produces:
            - application/json
        parameters:
        -   name: id
            in: path
            description: Gender id
            required: true
            type: integer
            example: 1
        responses:
            200:
                description: OK
                schema:
                    type: object
                    required:
                        - id
                        - name
                        - _links
                    properties:
                        id:
                            type: number
                            example: 1
                        name:
                            type: string
                            example: Girls
                        _links:
                            type: object
                            required:
                                - self
                            properties:
                                self:
                                    type: object
                                    required:
                                        - href
                                    properties:
                                        href:
                                            type: string
                                            format: uri
                                            example: http://localhost:8080/genders/1
            500:
                description: Internal server error
