/v1/divisions/{divisionId}/teams/{teamId}/replace:
    post:
        tags:
            - divisions
        summary: Replaces a team with another
        description: Replaces a team with another. This is a private endpoint.
        operationId: replaceTeam.js
        produces:
            - application/json
        parameters:
            -   name: divisionId
                in: path
                description: ID of the division
                required: true
                type: integer
                format: int64
            -   name: teamId
                in: path
                description: ID of the team
                required: true
                type: integer
                format: int64
            -   in: body
                name: body
                description: ID of the new team
                type: object
                schema:
                    type: object
                    properties:
                        teamId:
                            type: int
                            example: 1
                required: true
        responses:
            201:
                description: Created
            500:
                description: Internal server error
