/v1/operators/me/page/details:
    get:
        tags:
            - operator
        summary: Get operator defaults for pages
        description: Get operator defaults for pages. This is a private endpoint.
        operationId: getDetails.js
        produces:
            - application/json
        responses:
            200:
                description: OK
                schema:
                    type: object
                    required:
                        - logo_1
                        - logo_2
                        - logo_3
                        - notes
                        - social_media
                    properties:
                        logo_1:
                            type: string
                            example: URL
                        logo_2:
                            type: string
                            example: URL
                        logo_3:
                            type: string
                            example: URL
                        notes:
                            type: string
                            example: These are the default notes
                        social_media:
                            type: string
                            example: '@primetimesportz'
            500:
                description: Internal server error
