/v1/points:
    get:
        tags:
            - points
        summary: Get all the points
        description: Get all the points. This is a public endpoint.
        operationId: getPoints.js
        produces:
            - application/json
        responses:
            200:
                description: OK
                schema:
                    type: object
                    required:
                        - points
                    properties:
                        points:
                            type: array
                            items:
                                type: object
                                required:
                                    - id
                                    - name
                                    - values
                                    - points
                                properties:
                                    id:
                                        type: number
                                        example: 1
                                    name:
                                        type: string
                                        example: Points for a Win
                                    values:
                                        type: object
                                        example: {}
                                    points:
                                        type: number
                                        example: 1
                                    group:
                                        type: number
                                        example: 1
            500:
                description: Internal server error
